spring:
  datasource:
    url: jdbc:mysql://localhost:3306/prod_db
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: none # 운영 환경에서는 스키마 변경 금지
    show-sql: false  # 운영 환경에서는 SQL 출력 비활성화
server:
  port: 8000