spring:
  datasource:
    url: jdbc:mysql://localhost:3306/basic_db
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true